/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface": {
          DEFAULT: "var(--surface)",
          hover: "var(--surface-hover)",
        },
        "background": "var(--bg)",
        "on-surface": "var(--text)",
        "on-background": "var(--text)",
        "surface-variant": "var(--bg-secondary)",
        "on-surface-variant": "var(--text-secondary)",
        "surface-container": "var(--bg-tertiary)",
        "surface-dim": "var(--bg-secondary)",
        "surface-bright": "var(--surface)",
        "primary": "var(--accent)",
        "on-primary": "var(--surface)",
        "primary-container": "var(--accent-muted)",
        "on-primary-container": "var(--accent)",
        "secondary": "var(--text-secondary)",
        "tertiary": "var(--accent-hover)",
        "error": "var(--error)",
        border: {
          DEFAULT: 'var(--border)',
          hover: 'var(--border-hover)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          hover: 'var(--accent-hover)',
          muted: 'var(--accent-muted)',
        },
        txt: {
          DEFAULT: 'var(--text)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
        mono: ['SF Mono', 'Fira Code', 'monospace'],
        h2: ["Space Grotesk"],
        "display-xl": ["Space Grotesk"],
        "body-lg": ["Inter"],
        "label-caps": ["Space Grotesk"],
        "h3": ["Space Grotesk"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "h1": ["Space Grotesk"],
        "display-lg": ["Space Grotesk"],
        "button": ["Inter"]
      },
      fontSize: {
        "h2": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "display-xl": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700"}],
        "h3": ["24px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "h1": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "display-lg": ["56px", {"lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "700"}],
        "button": ["16px", {"lineHeight": "1", "fontWeight": "600"}],
        'display-sm': ['3rem', { lineHeight: 1.15, letterSpacing: '-0.02em' }],
        'heading-lg': ['2.25rem', { lineHeight: 1.2, letterSpacing: '-0.02em' }],
        'heading': ['1.875rem', { lineHeight: 1.25, letterSpacing: '-0.015em' }],
        'heading-sm': ['1.5rem', { lineHeight: 1.3, letterSpacing: '-0.01em' }],
        'caption': ['0.75rem', { lineHeight: 1.5, letterSpacing: '0.02em' }],
      },
      spacing: {
        "xl": "80px",
        "container-max": "1280px",
        "gutter": "24px",
        "xs": "4px",
        "md": "24px",
        "lg": "48px",
        "sm": "12px",
        "base": "8px",
        '18': '4.5rem',
        '22': '5.5rem',
        '26': '6.5rem',
        '30': '7.5rem',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      boxShadow: {
        glass: 'var(--shadow-glass)',
        glow: 'var(--shadow-glow)',
        'glass-hover': 'var(--shadow-glass-hover)',
      },
      backdropBlur: {
        glass: '20px',
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      transitionDuration: {
        '250': '250ms',
      },
      maxWidth: {
        container: '1280px',
        narrow: '960px',
        wide: '1440px',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out forwards',
        'fade-in-up': 'fadeInUp 0.6s ease-out forwards',
        'fade-in-down': 'fadeInDown 0.5s ease-out forwards',
        'scale-in': 'scaleIn 0.4s ease-out forwards',
        'slide-up': 'slideUp 0.5s ease-out forwards',
        'float': 'float 6s ease-in-out infinite',
        'pulse-soft': 'pulseSoft 3s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.8' },
        },
      },
    },
  },
  plugins: [],
};
